import { useEffect, useMemo, useState } from "react";
import { Atom, Bolt, CircleDot, Gauge, Orbit, Waves } from "lucide-react";

type Topic = "Kinematics" | "Forces" | "Energy" | "Momentum" | "Rotation" | "Electric Fields" | "Circuits" | "Waves" | "Thermodynamics";
type Params = Record<string, number>;
type ModelResult = { readout: Array<[string, string]>; [key: string]: any };
const TOPICS: { name: Topic; icon: typeof Orbit; color: string }[] = [
  { name: "Kinematics", icon: Orbit, color: "#9a8bff" }, { name: "Forces", icon: Gauge, color: "#ff8fb1" }, { name: "Energy", icon: Bolt, color: "#ffc46b" },
  { name: "Momentum", icon: CircleDot, color: "#6fd6c8" }, { name: "Rotation", icon: Orbit, color: "#9a8bff" }, { name: "Electric Fields", icon: Atom, color: "#6fd6c8" },
  { name: "Circuits", icon: Bolt, color: "#ffc46b" }, { name: "Waves", icon: Waves, color: "#ff8fb1" }, { name: "Thermodynamics", icon: Atom, color: "#ff8fb1" },
];
const defaults: Record<Topic, Params> = {
  Kinematics: { speed: 18, angle: 48, gravity: 9.8, height: 2 }, Forces: { force: 14, mass: 3, friction: .12 }, Energy: { mass: 2, height: 5, speed: 4, friction: .08 },
  Momentum: { m1: 2, m2: 1, v1: 5, v2: 0 }, Rotation: { force: 14, radius: .8, angle: 90, inertia: 2 }, "Electric Fields": { charge: 4, distance: 1 },
  Circuits: { voltage: 12, resistance: 20 }, Waves: { amplitude: .5, frequency: 2, speed: 8 }, Thermodynamics: { temperature: 300, volume: 2, particles: 45 },
};
function fmt(value: number, digits = 2) { return Number.isFinite(value) ? value.toFixed(digits) : "—"; }
function model(topic: Topic, p: Params, t: number): ModelResult {
  if (topic === "Kinematics") { const a = p.angle * Math.PI / 180, vx = p.speed * Math.cos(a), vy = p.speed * Math.sin(a), flight = (vy + Math.sqrt(vy * vy + 2 * p.gravity * p.height)) / p.gravity, time = Math.min(t, flight), x = vx * time, y = Math.max(0, p.height + vy * time - .5 * p.gravity * time ** 2); return { readout: [["x", `${fmt(x)} m`], ["y", `${fmt(y)} m`], ["vₓ", `${fmt(vx)} m/s`], ["vᵧ", `${fmt(vy - p.gravity * time)} m/s`], ["flight", `${fmt(flight)} s`]], equation: "x = vₓt · y = y₀ + vᵧt − ½gt²", x, y, vx, vy: vy - p.gravity * time, flight }; }
  if (topic === "Forces") { const friction = p.friction * p.mass * 9.8, net = p.force - friction, a = net / p.mass, x = .5 * a * t * t; return { readout: [["F net", `${fmt(net)} N`], ["a", `${fmt(a)} m/s²`], ["v", `${fmt(a * t)} m/s`], ["friction", `${fmt(friction)} N`]], equation: "ΣF = F − μmg = ma", x, a, net }; }
  if (topic === "Energy") { const thermal = p.friction * p.mass * 9.8 * Math.min(p.height + 2, 7), potential = p.mass * 9.8 * Math.max(0, p.height - t * .5), kinetic = .5 * p.mass * p.speed ** 2 + (p.mass * 9.8 * (p.height - Math.max(0, p.height - t * .5)) - thermal); return { readout: [["Kinetic", `${fmt(Math.max(0, kinetic))} J`], ["Gravitational", `${fmt(potential)} J`], ["Thermal", `${fmt(thermal)} J`]], equation: "E_total = K + U_g + E_thermal", kinetic: Math.max(0, kinetic), potential, thermal }; }
  if (topic === "Momentum") { const total = p.m1 * p.v1 + p.m2 * p.v2, vf = total / (p.m1 + p.m2), distance = t < 1.8 ? Math.max(0, p.v1 * t) : Math.max(0, p.vf ?? vf * (t - 1.8) + p.v1 * 1.8); return { readout: [["p initial", `${fmt(total)} kg·m/s`], ["v final", `${fmt(vf)} m/s`], ["K initial", `${fmt(.5 * p.m1 * p.v1 ** 2)} J`]], equation: "pᵢ = p_f = mv", total, vf, distance }; }
  if (topic === "Rotation") { const tau = p.radius * p.force * Math.sin(p.angle * Math.PI / 180), alpha = tau / p.inertia, theta = .5 * alpha * t * t; return { readout: [["τ", `${fmt(tau)} N·m`], ["α", `${fmt(alpha)} rad/s²`], ["ω", `${fmt(alpha * t)} rad/s`]], equation: "τ = rFsinθ · α = τ/I", tau, alpha, theta }; }
  if (topic === "Electric Fields") { const E = 8.99e9 * Math.abs(p.charge * 1e-6) / p.distance ** 2; return { readout: [["E", `${fmt(E, 0)} N/C`], ["charge", `${fmt(p.charge)} μC`], ["distance", `${fmt(p.distance)} m`]], equation: "E = k|q|/r²", E }; }
  if (topic === "Circuits") { const current = p.voltage / p.resistance; return { readout: [["I", `${fmt(current, 3)} A`], ["V", `${fmt(p.voltage)} V`], ["P", `${fmt(p.voltage * current)} W`]], equation: "V = IR · P = IV", current }; }
  if (topic === "Waves") { const lambda = p.speed / p.frequency; return { readout: [["λ", `${fmt(lambda)} m`], ["f", `${fmt(p.frequency)} Hz`], ["v", `${fmt(p.speed)} m/s`]], equation: "v = fλ", lambda }; }
  const pressure = p.particles * p.temperature * 5.56 / p.volume / 1000; return { readout: [["T", `${fmt(p.temperature, 0)} K`], ["P", `${fmt(pressure)} kPa`], ["V", `${fmt(p.volume)} L`]], equation: "PV = Nk_BT", pressure };
}
function Arrow({ x1, y1, x2, y2, color = "#ff8fb1", label }: { x1: number | string; y1: number | string; x2: number | string; y2: number | string; color?: string; label?: string }) { const angle = Math.atan2(Number(y2) - Number(y1), Number(x2) - Number(x1)); return <g><line x1={x1} y1={y1} x2={x2} y2={y2} stroke={color} strokeWidth="3" strokeLinecap="round" /><path d={`M ${x2} ${y2} l ${-9 * Math.cos(angle - .5)} ${-9 * Math.sin(angle - .5)} l ${9 * Math.cos(angle - .5) - 9 * Math.cos(angle + .5)} ${9 * Math.sin(angle - .5) - 9 * Math.sin(angle + .5)} z`} fill={color} />{label && <text x={(Number(x1) + Number(x2)) / 2 + 5} y={(Number(y1) + Number(y2)) / 2 - 5} fill={color} fontSize="11">{label}</text>}</g>; }
function Scene({ topic, p, time }: { topic: Topic; p: any; time: number }) { const m: any = model(topic, p, time); const color = TOPICS.find((x) => x.name === topic)?.color ?? "#9a8bff"; const points = Array.from({ length: 40 }, (_, i) => i / 39); if (topic === "Kinematics") { const a = p.angle * Math.PI / 180, flight = m.flight, scale = 420 / Math.max(1, p.speed * Math.cos(a) * flight); return <svg viewBox="0 0 640 300" className="showcase-svg" role="img" aria-label="Animated projectile kinematics model"><line x1="50" y1="250" x2="590" y2="250" stroke="#8b95ba" /><line x1="50" y1="250" x2="50" y2="45" stroke="#8b95ba" /><text x="580" y="270" fill="#a6afd3" fontSize="11">x (m)</text><text x="24" y="55" fill="#a6afd3" fontSize="11">y (m)</text><path d={points.map((u, i) => { const tt = u * flight, x = 50 + p.speed * Math.cos(a) * tt * scale, y = 250 - Math.max(0, p.height + p.speed * Math.sin(a) * tt - .5 * p.gravity * tt ** 2) * 25; return `${i ? "L" : "M"}${x},${y}`; }).join(" ")} fill="none" stroke={color} strokeWidth="2" strokeDasharray="5 7" /><circle cx={50 + m.x * scale} cy={250 - m.y * 25} r="13" fill={color} className="showcase-object" /><Arrow x1={50 + m.x * scale} y1={250 - m.y * 25} x2={50 + m.x * scale + m.vx * 5} y2={250 - m.y * 25 - m.vy * 5} color="#6fd6c8" label="v" /><Arrow x1={50 + m.x * scale} y1={250 - m.y * 25} x2={50 + m.x * scale} y2={250 - m.y * 25 + 35} color="#ff8fb1" label="g" /><text x="320" y="22" textAnchor="middle" fill="#e9ecff" fontSize="15" fontWeight="bold">Projectile trajectory · t = {fmt(time)} s</text></svg>; }
  if (topic === "Forces") return <svg viewBox="0 0 640 300" className="showcase-svg" role="img" aria-label="Interactive free body diagram"><line x1="70" y1="245" x2="570" y2="245" stroke="#8b95ba" strokeWidth="4" /><rect x={260 + Math.min(150, Math.max(-50, m.x * 2))} y="190" width="80" height="55" rx="10" fill={color} /><Arrow x1="300" y1="190" x2="300" y2="110" color="#ff8fb1" label="mg" /><Arrow x1="300" y1="220" x2={300 + p.force * 7} y2="220" color="#ffc46b" label="F" /><Arrow x1="300" y1="232" x2={300 - p.friction * p.mass * 9.8 * 7} y2="232" color="#6fd6c8" label="f" /><text x="320" y="30" textAnchor="middle" fill="#e9ecff" fontSize="15" fontWeight="bold">Cart · a = {fmt(m.a)} m/s²</text></svg>;
  if (topic === "Energy") return <svg viewBox="0 0 640 300" className="showcase-svg" role="img" aria-label="Energy transfer model"><path d="M70 235 L250 90 L570 235" fill="none" stroke="#8b95ba" strokeWidth="4" /><circle cx={110 + Math.min(390, time * 55)} cy={220 - Math.sin(Math.min(Math.PI, time * .7)) * 120} r="14" fill={color} className="showcase-object" /><g transform="translate(430 55)"><text fill="#a6afd3" fontSize="11">ENERGY (J)</text>{([['K', m.kinetic, '#6fd6c8'], ['Uᵍ', m.potential, '#ffc46b'], ['thermal', m.thermal, '#ff8fb1']] as Array<[string, number, string]>).map(([label, value, fill], i) => <g key={String(label)} transform={`translate(0 ${25 + i * 48})`}><text fill="#e9ecff" fontSize="11">{label}</text><rect x="55" y="-11" width={Math.min(135, Math.max(4, Number(value) * 2))} height="16" rx="8" fill={String(fill)} /><text x="200" y="1" fill="#a6afd3" fontSize="10">{fmt(Number(value))}</text></g>)}</g></svg>;
  if (topic === "Momentum") return <svg viewBox="0 0 640 300" className="showcase-svg" role="img" aria-label="Collision model"><line x1="45" y1="240" x2="595" y2="240" stroke="#8b95ba" strokeWidth="4" /><circle cx={145 + Math.min(180, time * 75)} cy="210" r={18 + p.m1 * 3} fill="#9a8bff" /><circle cx={455 - Math.min(180, time * 75)} cy="210" r={18 + p.m2 * 3} fill="#6fd6c8" /><Arrow x1="110" y1="155" x2="170" y2="155" color="#ffc46b" label="p₁" /><Arrow x1="490" y1="155" x2="440" y2="155" color="#ffc46b" label="p₂" /><text x="320" y="30" textAnchor="middle" fill="#e9ecff" fontSize="15" fontWeight="bold">Collision · p = {fmt(m.total)} kg·m/s</text></svg>;
  if (topic === "Rotation") { const angle = m.theta, cx = 280, cy = 155, r = 95; return <svg viewBox="0 0 640 300" className="showcase-svg" role="img" aria-label="Rotational dynamics model"><circle cx={cx} cy={cy} r="18" fill="#ffc46b" /><line x1={cx} y1={cy} x2={cx + Math.cos(angle) * r} y2={cy + Math.sin(angle) * r} stroke={color} strokeWidth="18" strokeLinecap="round" /><Arrow x1={cx + Math.cos(angle) * r} y1={cy + Math.sin(angle) * r} x2={cx + Math.cos(angle) * r + Math.cos(angle + p.angle * Math.PI / 180) * 85} y2={cy + Math.sin(angle) * r + Math.sin(angle + p.angle * Math.PI / 180) * 85} color="#ff8fb1" label="F" /><text x="320" y="30" textAnchor="middle" fill="#e9ecff" fontSize="15" fontWeight="bold">Rotating beam · τ = {fmt(m.tau)} N·m</text><text x="320" y="275" textAnchor="middle" fill="#a6afd3" fontSize="12">r = {p.radius} m · α = {fmt(m.alpha)} rad/s²</text></svg>; }
  if (topic === "Electric Fields") return <svg viewBox="0 0 640 300" className="showcase-svg" role="img" aria-label="Electric field map"><circle cx="320" cy="150" r="24" fill={p.charge >= 0 ? "#ff8fb1" : "#6fd6c8"} /><text x="320" y="155" textAnchor="middle" fill="#fff">{p.charge >= 0 ? "+q" : "−q"}</text>{Array.from({ length: 16 }, (_, i) => { const a = i * Math.PI / 8, l = Math.min(110, 35 + m.E / 250); return <Arrow key={i} x1={320 + Math.cos(a) * 32} y1={150 + Math.sin(a) * 32} x2={320 + Math.cos(a) * l} y2={150 + Math.sin(a) * l} color="#6fd6c8" />; })}<text x="320" y="30" textAnchor="middle" fill="#e9ecff" fontSize="15" fontWeight="bold">Field vectors · E = {fmt(m.E, 0)} N/C</text></svg>;
  if (topic === "Circuits") return <svg viewBox="0 0 640 300" className="showcase-svg" role="img" aria-label="Ohm's law circuit"><path d="M110 70 H530 V235 H110 Z" fill="none" stroke="#8b95ba" strokeWidth="3" /><line x1="180" y1="55" x2="180" y2="85" stroke="#ffc46b" strokeWidth="8" /><line x1="205" y1="62" x2="205" y2="78" stroke="#ffc46b" strokeWidth="3" /><rect x="285" y="51" width="100" height="40" rx="8" fill="#9a8bff" /><text x="335" y="76" textAnchor="middle" fill="#fff" fontSize="12">R = {p.resistance} Ω</text><Arrow x1="120" y1="70" x2={275 + m.current * 25} y2="70" color="#6fd6c8" label={`I = ${fmt(m.current, 2)} A`} /><text x="320" y="280" textAnchor="middle" fill="#e9ecff" fontSize="15" fontWeight="bold">P = {fmt(p.voltage * m.current)} W</text></svg>;
  if (topic === "Waves") return <svg viewBox="0 0 640 300" className="showcase-svg" role="img" aria-label="Traveling wave model"><line x1="45" y1="150" x2="595" y2="150" stroke="#8b95ba" /><path d={Array.from({ length: 100 }, (_, i) => { const x = 45 + i * 5.5, y = 150 - p.amplitude * 85 * Math.sin(i / 99 * Math.PI * 8 - time * p.frequency * 2); return `${i ? "L" : "M"}${x},${y}`; }).join(" ")} fill="none" stroke={color} strokeWidth="4" /><text x="320" y="30" textAnchor="middle" fill="#e9ecff" fontSize="15" fontWeight="bold">Wave · λ = {fmt(m.lambda)} m</text><text x="320" y="280" textAnchor="middle" fill="#a6afd3" fontSize="12">A = {p.amplitude} m · f = {p.frequency} Hz · v = {p.speed} m/s</text></svg>;
  const width = Math.max(200, p.volume * 75); return <svg viewBox="0 0 640 300" className="showcase-svg" role="img" aria-label="Thermodynamic particle model"><rect x="170" y="55" width={width} height="185" fill="#9a8bff20" stroke="#9a8bff" strokeWidth="3" />{Array.from({ length: Math.round(p.particles / 2) }, (_, i) => <circle key={i} cx={185 + ((i * 37 + Math.sin(time * (i + 1)) * p.temperature / 12) % Math.max(25, width - 25))} cy={72 + ((i * 27 + Math.cos(time * (i + 2)) * p.temperature / 14) % 145)} r="4" fill={p.temperature > 400 ? "#ff8fb1" : "#6fd6c8"} />)}<text x="320" y="30" textAnchor="middle" fill="#e9ecff" fontSize="15" fontWeight="bold">Particle gas · P = {fmt(m.pressure)} kPa</text><text x="320" y="280" textAnchor="middle" fill="#a6afd3" fontSize="12">T = {p.temperature} K · V = {p.volume} L · N = {p.particles}</text></svg>;
}
export function InteractivePhysicsShowcase() { const [active, setActive] = useState<Topic>("Kinematics"); const [params, setParams] = useState<Record<Topic, Params>>(defaults); const [running, setRunning] = useState(true); const [time, setTime] = useState(1.2); useEffect(() => { if (!running) return; let raf = 0, last = performance.now(); const tick = (now: number) => { setTime((value) => (value + Math.min(.04, (now - last) / 1000)) % 8); last = now; raf = requestAnimationFrame(tick); }; raf = requestAnimationFrame(tick); return () => cancelAnimationFrame(raf); }, [running]); const p = params[active] as Params; const m = useMemo(() => model(active, p, time), [active, p, time]); const topic = TOPICS.find((x) => x.name === active)!; const controls = Object.entries(p); return <div className="showcase-interactive"><div className="showcase-topic-rail">{TOPICS.map(({ name, icon: Icon, color }) => <button key={name} onClick={() => { setActive(name); setTime(1.2); }} className={active === name ? "active" : ""}><Icon className="size-3.5" style={{ color }} /><span>{name}</span></button>)}</div><div className="showcase-stage"><div className="showcase-stage-top"><span><i /> live {active.toLowerCase()} model</span><button onClick={() => setRunning((x) => !x)}>{running ? "Pause" : "Run"}</button></div><Scene topic={active} p={p} time={time} /><div className="showcase-equation"><small>{active.toUpperCase()}</small><b>{m.equation}</b></div></div><div className="showcase-controls"><div className="control-header"><span>Control the model</span><small>every input has a consequence</small></div>{controls.slice(0, 4).map(([key, value]) => { const limits = active === "Kinematics" ? { speed: [4, 30, 1], angle: [10, 80, 1], gravity: [2, 18, .5], height: [0, 10, .5] }[key] : undefined; const [min, max, step] = limits ?? [0, Math.max(1, value * 2), value < 1 ? .01 : 1]; return <label key={key}><span>{key} <b>{fmt(value, step < .1 ? 2 : 1)}</b></span><input type="range" min={min} max={max} step={step} value={value} onChange={(e) => setParams((all) => ({ ...all, [active]: { ...all[active], [key]: Number(e.target.value) } }))} /></label>; })}<div className="showcase-readouts">{m.readout.map(([key, value]) => <span key={key}><small>{key}</small><b>{value}</b></span>)}</div></div></div>; }
